### ISSUE TITLE
Rotate mode minor error

### ISSUE THREAD

**Issue by tkdwns414** [CSID-DGU/2021-OSSPC-CHUPARKIM-5#14]
1. rotate.py 에서 게임 진행 키 변경으로 인해 사운드 재생에서 오류가 있습니다. 
기존 코드의 경우 블록이 왼쪽 이동을 위해 K_LEFT를 입력하였을 때 "사운드 1" 재생
-> rotate.py 코드의 경우 2회전 상태에서 K_LEFT를 입력하였을 때 실제 블록은 오른쪽으로 이동하나 동일하게 "사운드 1"이 재생
해당 현상을 막기 위해 사운드 재생 관련 부분 코드 수정이 필요합니다.

2.  rotate.py에서 화면이 돌아갔을 때 사이드 바의 텍스트를 돌리는 방법까지는 알아냈고 구현해놨으나 텍스트가 올바른 곳에 나타나도록 코딩해두지 못했습니다. 하지만 화면 비율을 보아하니 (게임판 크기 감소 / 전체 게임창 크기 증가) 둘 중 하나는 이루어져야 할 것 같아 구체적인 계산을 진행하지 않았습니다.

**Comment by jaythenotorious** [comment]
향후 추가할 배경이미지와 게임플레이되는 화면의 결합을 고려해서, 사이드바 + 테트리스가 가급적 정방형이 되었으면 좋겠습니다
